<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $resources
 * @var \Deduplicate\Form\DeduplicateForm $form
 * @var string $resourceType
 * @var array $query
 * @var \Omeka\Api\Representation\PropertyRepresentation $property
 * @var string $value
 * @var string $method
 * @var int $totalResourcesQuery
 * @var int $totalResources
 */

// $maxResources = $this->setting('pagination_per_page') ?: \Omeka\Stdlib\Paginator::PER_PAGE;
$maxResources = \Deduplicate\Controller\IndexController::MAX_TO_MERGE;

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->htmlElement('body')->appendAttribute('class', 'deduplicate resources show');

$form->prepare();

$hasMultipleResources = $totalResources > 1;
$isPost = $property && strlen($value);
?>

<?= $this->pageTitle($translate('Deduplicate resources')) ?>

<?php if ($query): ?>

    <p class="explanation">
        <?= sprintf('The query filtering resources returned %d resources.', $totalResourcesQuery) ?>
    </p>

<?php endif; ?>

<p class="explanation">
    <?= sprintf($translate('Select a property and a value to process a new merge, or go to %sresources%s to filter them first.'), '<a href="' . $url('admin/default', ['controller' => 'item']) . '"/>', '</a>') ?>
</p>

<?= $this->form($form); ?>

<?php if (!$totalResources): ?>
    <?php if ($isPost): ?>
    <p class="explanation">
        <?= sprintf($translate('The query returned no results.')) ?>
    </p>
    <?php endif; ?>
<?php else: ?>
    <?php if ($totalResources === 1): ?>
    <p class="explanation">
        <?= sprintf($translate('The query returned a single result.')) ?>
    </p>
    <?php elseif ($totalResources > $maxResources): ?>
    <p class="explanation">
        <?= $escape(sprintf($translate('The search returned %1$d resources. Only %2$d first ones are displayed. Other ones won’t be processed.'), $totalResources, $maxResources)) ?>
    </p>
    <?php endif; ?>

    <?php if ($hasMultipleResources): ?>
    <form id="deduplicate-resource" method="POST" name="deduplicate-resource">
        <input type="hidden" name="query" value="<?= $escapeAttr(json_encode($query ?: array_keys($resources), 320)) ?>"/>
        <input type="hidden" name="resource_type" value="<?= $escapeAttr($resourceType) ?>"/>
        <input type="hidden" name="deduplicate_property" value="<?= $property ? $escapeAttr($property->term()) : '' ?>"/>
        <input type="hidden" name="deduplicate_value" value="<?= $escapeAttr($value) ?>"/>
        <input type="hidden" name="method" value="<?= $escapeAttr($method) ?>"/>
        <p>
            <?= $translate('Select the resource to keep and the ones to merge:') ?>
        </p>
    <?php endif; ?>

    <?php foreach ($resources as $resource): ?>

    <hr/>

    <?php if ($hasMultipleResources): ?>
    <div>
        <input type="radio" name="resource_id" value="<?= $resource->id() ?>" aria-label="<?= $translate('Select resource to keep') ?>" required="required"/>
        <input type="checkbox" name="resources_merged[]" value="<?= $resource->id() ?>" aria-label="<?= $translate('Select resource to merge') ?>"/>
    </div>
    <?php endif; ?>

    <?= $resource->linkPretty() ?>

    <div id="item-metadata" class="active section">
        <?php if ($resource->resourceTemplate()): ?>
            <div class="meta-group">
                <h4><?= $translate('Template');?></h4>
                <div class="value"><?= $escape($translate($resource->resourceTemplate()->label())) ?></div>
            </div>
        <?php endif; ?>
        <?php if ($resource->resourceClass()): ?>
            <div class="meta-group">
                <h4><?= $translate('Class') ?></h4>
                <div class="value"><?= $escape($translate($resource->resourceClass()->label())) ?></div>
            </div>
        <?php endif; ?>
        <?= $resource->displayValues() ?>
    </div>

    <?php endforeach; ?>

    <?php if ($hasMultipleResources): ?>
    </form>
    <?php endif; ?>

<?php endif; ?>

<div id="page-actions">
    <?= $this->cancelButton() ?>
    <button type="submit" name="deduplicate_all" form="deduplicateform"><?= $escape('Search') ?></button>
    <?php if ($hasMultipleResources && $isPost): ?>
    <button type="submit" name="deduplicate_submit" form="deduplicate-resource"><?= $escape('Merge') ?></button>
    <?php endif; ?>
</div>
